Algoritmo "DeumaDez"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa Dos Santos
// Descrição   :
// Autor(a)    : Nicolas Daniel
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contadora<- 1
enquanto contadora < = 10 faca
escreval(contadora)
contadora<- contadora + 1
fimenquanto
Fimalgoritmo